import { getRandomInArray } from '../utils/random.util';

export const bookList =  [
  'Odisseia, de Homero',
  'Os Irmãos Karamazov (1880), de Fiódor Dostoiévski',
  'Crime e Castigo (1866), de Fiódor Dostoiévski',
  'Madame Bovary (1856), de Gustave Flaubert',
  'Divina Comédia (1472), de Dante Alighieri',
  'As Aventuras de Huckleberry Finn (1884), de Mark Twain',
  'Alice no País das Maravilhas (1865), de Lewis Carroll',
  'Orgulho e Preconceito (1812), de Jane Austen',
  'O Morro dos Ventos Uivantes (1847), Emily Brontë',
  'Ao Farol (1927), Virginia Woolf',
  'Ardil-22 (1961), de Joseph Heller',
  'O Som e A Fúria (1929), William Faulkner',
  '1984 (1949), de George Orwell',
  'Anna Karenina (1877), Lev Tolstói',
  'Ilíada, de Homero',
  'O Coração das Trevas (1902), de Joseph Conrad',
  'As Vinhas da Ira (1939), de John Steinbeck',
  'Homem Invisível (1952), de Ralph Ellison',
  'O Sol é Para Todos (1960), de Harper Lee',
  'Middlemarch: Um Estudo da Vida Provinciana (1871), de George Eliot',
  'Grandes Esperanças (1861), Charles Dickens',
  'As Viagens de Gulliver (1726), de Jonathan Swift',
  'Absalão, Absalão! (1936), de William Faulkner',
  'Amada (1987), de Toni Morrison',
  'O Estrangeiro (1942), de Albert Camus',
  'Jane Eyre (1847), de Charlotte Brontë',
  'As Mil e Uma Noites (Contos da Índia, Irã, Iraque e Egito)',
  'O Processo (1925), de Franz Kafka',
  'O Vermelho e o Negro (1830), de Stendhal',
  'Mrs Dalloway (1925), de Virginia Woolf',
  'Contos de Anton Chekhov, de Anton Tchekhov',
  'O Sol Também se Levanta (1926), de Ernest Hemingway',
  'David Copperfield (1850), de Charles Dickens',
  'Retrato do Artista Quando Jovem (1916), de James Joyce',
  'Os Filhos da Meia-Noite (1981), Salman Rushdie',
  'Ficções (1944), de Jorge Luis Borges',
  'A Vida e as Opiniões de Tristram Shandy (1759), de Laurence Sterne',
  'Folhas de Relva (1855), Walt Whitman',
  'Eneida (19 a.C.), de Virgílio',
  'Cândido, ou O Otimismo (1759), de Voltaire',
  'O Senhor dos Anéis (1954), de J. R. R. Tolkien',
  'Os Miseráveis (1862), de Victor Hugo',
  'A Montanha Mágica (1924), de Thomas Mann',
  'Uma Passagem Para a Índia (1924), de Edward Morgan Foster',
  'O Velho e o Mar (1952), de Ernest Hemingway',
  'O Mundo se Despedaça (1958), de Chinua Achebe',
  'Por Quem os Sinos Dobram (1940), de Ernest Hemingway',
  'As Histórias Completas de Franz Kafka (1971), de Franz Kafka',
  'Retrato de Uma Senhora (1881), de Henry James',
  'Fogo Pálido (1962), de Vladimir Nabokov',
  'O Idiota (1869), de Fiódor Dostoiévski',
  'Enquanto Agonizo (1930), de William Faulkner',
  'Édipo Rei (427 a.C.), de Sófocles',
  'A Cor Púrpura (1982), Alice Walker',
  'E O Vento Levou (1936), de Margaret Mitchell',
  'O Senhor das Moscas (1954), de William Golding',
  'Admirável Mundo Novo (1932), de Aldous Huxley',
  'Os Melhores Contos e Poemas de Edgar Allan Poe (1849), de Edgar Allan Poe',
  'Emma (1815), de Jane Austen',
  'A Época da Inocência (1920), Edith Wharton',
  'Almas Mortas (1842), de Nikolai Gogol',
  'On The Road: Pé na Estrada (1957), de Jack Kerouac',
  'O Bom Soldado (1915), de Ford Madox Ford',
  'A Revolução dos Bichos (1945), de George Orwell',
  'Os Contos da Cantuária (1932), de Geoffrey Chaucer',
  'A Metamorfose (1915), de Franz Kafka',
  'Frankenstein (1823), de Mary Shelley',
  'Feira das Vaidades (1847), de William Makepeace Thackeray',
  'À Sombra do Vulcão (1947), de Malcolm Lowry',
  'A Terra Inútil (1922), de T. S. Eliot',
  'Adeus às Armas (1929), de Ernest Hemingway',
  'Journey to the End of the Night (1932), de Louis-Ferdinand Céline',
  'O Castelo (1926), de Franz Kafka',
  'A Educação Sentimental (1869), de Gustave Flaubert',
  'A Letra Escarlate (1850), de Nathaniel Hawthorne',
  'Matadouro 5 (1969), de Kurt Vonnegut',
  'O Conto da Aia (1985), de Margaret Atwood',
  'Charlotte’s Web (1952), de Elwyn Brooks White',
  'Native Son (1940), Richard Wright',
  'Paraíso Perdido (1667), de John Milton',
  'Gargântua e Pantagruel (1532), de François Rabelais',
  'Fausto (1829), de Johann Wolfgang von Goethe',
  'Rebecca (1938), de Daphne du Maurier',
  'Os Demônios (1871), de Fiódor Dostoiévski',
  'As Flores do Mal (1857), de Charles Baudelaire',
  'Antígona (442 a.C.), de Sófocles',
  'Tess Dos D’Urbervilles (1981), de Thomas Hardy',
  'Robinson Crusoe (1719), de Daniel Defoe',
  'Seus Olhos Viam Deus (1937), de Zora Neale Hurston',
  'Tom Jones (1749), de Henry Fielding',
];

export const getRandomBook = () => {
  return getRandomInArray(bookList);
}