import { getRandomInArray } from "../utils/random.util";

export const cityList =  [
  'São Paulo',
  'Rio de Janeiro',
  'Brasília',
  'Salvador',
  'Fortaleza',
  'Belo Horizonte',
  'Manaus',
  'Curitiba',
  'Recife',
  'Goiânia',
  'Belém',
  'Porto Alegre',
  'Guarulhos',
  'Campinas',
  'São Luís',
  'São Gonçalo',
  'Maceió',
  'Duque de Caxias',
  'Bandeira de Campo Grande',
  'Natal',
  'Teresina',
  'São Bernardo do Campo',
  'Nova Iguaçu',
  'João Pessoa',
  'São José dos Campos',
  'Santo André',
  'Ribeirão Preto',
  'Jaboatão dos Guararapes',
  'Osasco',
  'Uberlândia',
  'Sorocaba',
  'Contagem',
  'Aracaju',
  'Feira de Santana',
  'Cuiabá',
  'Joinville',
  'Aparecida de Goiânia',
  'Londrina',
  'Juiz de Fora',
  'Porto Velho',
  'Ananindeua',
  'Serra',
  'Caxias do Sul',
  'Niterói',
  'Belford Roxo',
  'Macapá',
  'Campos dos Goytacazes Campos dos Goytacazes',
  'Florianópolis',
  'Vila Velha',
  'Mauá',
  'São João de Meriti',
  'São José do Rio Preto',
  'Mogi das Cruzes',
  'Betim',
  'Santos',
  'Maringá',
  'Diadema',
  'Jundiaí',
  'Boa Vista',
  'Montes Claros',
  'Rio Branco',
  'Campina Grande',
  'Piracicaba',
  'Carapicuíba',
  'Olinda',
  'Anápolis',
  'Cariacica',
  'Bauru',
  'Itaquaquecetuba',
  'São Vicente',
  'Vitória',
  'Bandeira de Caruaru',
  'Caucaia',
  'Blumenau',
  'Franca',
  'Ponta Grossa',
  'Petrolina',
  'Canoas',
  'Pelotas',
  'Vitória da Conquista',
  'Ribeirão das Neves',
  'Uberaba',
  'Paulista',
  'Cascavel',
  'Praia Grande',
  'São José dos Pinhais',
  'Guarujá',
  'Taubaté',
  'Limeira',
  'Petrópolis',
  'Santarém',
  'Palmas',
  'Camaçari',
  'Mossoró',
  'Suzano',
  'Taboão da Serra',
  'Várzea Grande',
  'Sumaré',
  'Santa Maria',
  'Gravataí',
  'Marabá',
  'Governador Valadares',
  'Barueri',
  'Embu das Artes',
  'Juazeiro do Norte',
  'Volta Redonda',
  'Parnamirim',
  'Ipatinga',
  'Macaé',
  'Imperatriz',
  'Foz do Iguaçu',
  'Viamão',
  'Indaiatuba',
  'São Carlos',
  'Cotia',
  'São José',
  'Novo Hamburgo',
  'Colombo',
  'Magé',
  'Itaboraí',
  'Americana',
  'Sete Lagoas',
  'Rio Verde',
  'Itapevi',
  'Marília',
  'Divinópolis',
  'São Leopoldo',
  'Araraquara',
  'Rondonópolis',
  'Jacareí',
  'Hortolândia',
  'Arapiraca',
  'Cabo Frio',
  'Presidente Prudente',
  'Maracanaú',
  'Dourados',
  'Chapecó',
  'Itajaí',
  'Santa Luzia',
  'Juazeiro',
  'Águas Lindas de Goiás',
  'Criciúma',
  'Itabuna',
  'Parauapebas',
  'Bandeira de Rio Grande',
  'Luziânia',
  'Alvorada',
  'Sobral',
  'Cachoeiro de Itapemirim',
  'Cabo de Santo Agostinho',
  'Rio Claro',
  'Angra dos Reis',
  'Passo Fundo',
  'Castanhal',
  'Lauro de Freitas',
  'Araçatuba',
  'Ferraz de Vasconcelos',
  'Santa Bárbara d Oeste',
  'Nova Friburgo',
  'Nossa Senhora do Socorro',
  'Barra Mansa',
  'Teresópolis',
  'Araguaína',
  'Guarapuava',
  'Ibirité',
  'Jaraguá do Sul',
  'São José de Ribamar',
  'Itapecerica da Serra',
  'Francisco Morato',
  'Linhares',
  'Mesquita',
  'Itu',
  'Palhoça',
  'Valparaíso de Goiás',
  'Bragança Paulista',
  'Timon',
  'Pindamonhangaba',
  'Poços de Caldas',
  'Itapetininga',
  'Caxias',
  'Maricá',
  'Nilópolis',
  'Teixeira de Freitas',
  'São Caetano do Sul',
  'Ilhéus',
  'Abaetetuba',
  'Camaragibe',
  'Lages',
  'Barreiras',
  'Franco da Rocha',
  'Paranaguá',
  'Jequié',
  'Rio das Ostras',
  'Patos de Minas',
  'Parnaíba',
  'Mogi Guaçu',
  'Pouso Alegre',
  'Alagoinhas',
  'Jaú',
  'Queimados',
  'Porto Seguro',
  'Botucatu',
  'Bandeira araucaria',
  'Sinop',
  'Bandeira de Balneário Camboriú',
  'Atibaia',
  'Bandeira Toledo PR',
  'Santana de Parnaíba',
  'Sapucaia do Sul',
  'Teófilo Otoni',
  'BandeiraGaranhuns',
  'Bandeira vitoria de santo antao',
  'Cametá',
  'Barbacena',
  'Brusque',
  'Bandeira Santa Rita',
  'Sabará',
  'Varginha',
  'Bandeira apucarana',
  'Bandeira de Simões Filho',
  'Araras',
  'Itaguaí',
  'Araruama',
  'Bandeira Campo-Largo',
  'Flag of Marituba',
  'Bandeira de Pinhais',
  'Crato',
  'São Mateus',
  'Resende',
  'Cubatão',
  'Bandeira de Santa Cruz do Sul',
  'Bandeira de Cachoeirinha',
  'Valinhos',
  'Itapipoca',
  'Bandeira maranguape',
  'Ji-Paraná',
  'Trindade',
  'Vespasiano',
  'Conselheiro Lafaiete',
  'Bragança',
  'Sertãozinho',
  'Flag of Barcarena',
  'Uruguaiana-bandeira',
  'Guarapari',
  'Jandira',
  'Birigui',
  'Ribeirão Pires',
  'Bandeira de Paço do Lumiar',
  'Votorantim',
  'Colatina',
  'Caraguatatuba',
  'Três Lagoas',
  'Santana',
  'Várzea Paulista',
  'Tatuí',
  'Barretos',
  'Itatiba',
  'Guaratinguetá',
  'Catanduva',
  'Bento Gonçalves',
  'Bandeira Bage',
  'Itabira',
  'Bandeira almirante tamandare',
  'Salto',
  'Bandeira de Paulo Afonso',
  'Bandeira de Senador Canedo',
  'Igarassu',
  'Poá',
  'Araguari',
  'Bandeira de Novo Gama',
  'Ubá',
  'Parintins',
  'Passos',
  'Bandeira de Piraquara',
  'Bandeira eunapolis',
  'Ourinhos',
  'São Lourenço da Mata',
  'Bandeira-acailandia',
  'Corumbá',
  'Paulínia',
  'Bandeira de Catalão',
  'Coronel Fabriciano',
  'Bandeira scc',
  'Ariquemes',
  'Muriaé',
  'Bandeira Cambe Parana Brasil',
  'Araxá',
  'Erechim',
  'Bandeira.tubarão',
  'São Pedro da Aldeia',
  'Flag of Itumbiara GO',
  'Tangará da Serra',
  'Japeri',
  'BandeiraNovaSerrana',
  'Ituiutaba',
  'Lagarto',
  'Assis',
  'Bandeira de Bacabal',
  'Bandeira-lavras',
  'Leme',
  'Itaperuna',
  'São Gonçalo do Amarante',
  'Breves',
  'Itanhaém',
  'Aracruz',
  'Iguatu',
  'Caieiras',
  'Itacoatiara',
  'Bandeira de Santo Antônio de Jesus',
  'Vilhena',
  'Jataí',
  'Fazenda Rio Grande',
  'Mairiporã',
  'Itaituba',
  'Barra do Piraí',
  'Abreu e Lima',
];

export const getRandomCity = () => {
  return getRandomInArray(cityList);
}